#!/bin/bash
# Pull latest changes, discarding locally generated files
# (state.json and tournament.json are regenerated by the daemon)
set -e
cd "$(dirname "$0")/.."
git checkout -- docs/data/state.json data/tournament.json 2>/dev/null || true
git pull
